export const mockPharmacyData = [
    {
      id: 0,
      name: "Tai Man Pharmacy",
      phone: "5123 4567",
      email: "taiman@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 1,
      name: "Sai Man Pharmacy",
      phone: "5123 4568",
      email: "saiman@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 2,
      name: "Tin Man Pharmacy",
      phone: "5123 4569",
      email: "tinman@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 3,
      name: "Siu Man Pharmacy",
      phone: "5123 4561",
      email: "siuman@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 4,
      name: "Man Man Pharmacy",
      phone: "5123 4562",
      email: "manman@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 5,
      name: "Tai Tai Pharmacy",
      phone: "5123 4567",
      email: "taitai@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 6,
      name: "Sai Sai Pharmacy",
      phone: "5123 4568",
      email: "saisai@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 7,
      name: "Tin Tin Pharmacy",
      phone: "5123 4569",
      email: "tintin@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
    {
      id: 8,
      name: "Siu Siu Pharmacy",
      phone: "5123 4561",
      email: "siusiu@gmail.com",
      address: "Room 123",
      specialty: "Cardiology",
      district: "Kowloon",
    },
  ];
  